name: Build docs

on:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.11
    - name: Configure git
      run: |
        git config --global user.name "docs bot"
        git config --global user.email "<>"
    - name: Update documentation
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        docsrc/build
    - name: Publish docs to GitHub pages (docs branch)
      run: |
        git add docs -f
        git commit docs -m "Updating Documentation"
        git push origin main:docs -f
