name: Version

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Configure git
      run: |
        git config --global user.name "version bot"
        git config --global user.email "<>"
    - name: Increment version, tag branch
      run: |
        OLD_VERSION=$(grep version titans/__init__.py | grep -Po "\d+.\d+.\d+")
        NEW_VERSION=$(echo $OLD_VERSION | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e')
        for file in titans/__init__.py docsrc/conf.py; do
            sed s/$OLD_VERSION/$NEW_VERSION/g $file -i
            git add $file
        done
        git commit -m "Release $NEW_VERSION [no ci]"
        git tag $NEW_VERSION
    - name: Push to main
      run: |
        git push origin main:main -f
    - name: Push tag
      run: |
        VERSION=$(grep version titans/__init__.py | grep -Po "\d+.\d+.\d+")
        git push origin $VERSION
